application:
  name: tpr-frontend
  project: TheParisianRestaurant
  cloud_region: aws/us-east-2
  publicly_accessible: true
routers:
- name: frontend
  custom_domains:
  - branch: master
    domain: parisian.qvy.io
  routes:
  - application_name: tpr-frontend
    paths:
    - /
